---
- hosts: ts-elastic
  roles:
    - elastic
  environment:
    ELASTIC_STACK_VERSION: "8.1.0"
    KIBANA_URL: "http://192.168.56.10:5601"
    KIBANA_AUTH: "vagrant:vagrant"
    ELASTICSEARCH_URL: "https://192.168.56.10:9200"
    FLEET_SERVER_URL: "https://192.168.56.10:8220"
  tags: ts-elastic

- hosts: ts-debian11
  roles:
    - debian11
  environment:
    ELASTIC_STACK_VERSION: "8.1.0"
    KIBANA_URL: "http://192.168.56.10:5601"
    KIBANA_AUTH: "vagrant:vagrant"
    ELASTICSEARCH_URL: "https://192.168.56.10:9200"
    FLEET_SERVER_URL: "https://192.168.56.10:8220"
  tags: ts-debian11

- hosts: ts-windows10
  roles:
    - windows10
  environment:
    ELASTIC_STACK_VERSION: "8.1.0"
    KIBANA_URL: "http://192.168.56.10:5601"
    KIBANA_AUTH: "vagrant:vagrant"
    ELASTICSEARCH_URL: "https://192.168.56.10:9200"
    FLEET_SERVER_URL: "https://192.168.56.10:8220"
  tags: ts-windows10

- hosts: ts-redops
  roles:
    - redops
  tags: ts-redops

- hosts: ts-esxi
  roles:
    - esxi
  tags: ts-esxi
