---
- hosts: ts-elastomic
  roles:
    - elastomic
  environment:
    KIBANA_AUTH: vagrant:vagrant
  tags: ts-elastomic

- hosts: ts-centos7
  roles:
    - centos
  environment:
    KIBANA_AUTH: vagrant:vagrant
  tags: ts-centos7

- hosts: ts-windows10
  roles:
    - windows10
  tags: ts-windows10