---

- name: Set hostname to ts-elastomic
  hostname:
    name: ts-elastomic
  become: yes

- name: Create a directory if it does not exist
  file:
    path: /vagrant/scripts
    state: directory
    mode: '0755'
  become: yes

- name: Copy vagrant resources
  synchronize:
    src: ./files/
    dest: /vagrant/scripts/
  become: yes

- name: Copy the interface file over as root
  shell: "mv /vagrant/scripts/ifcfg-ens33 /etc/sysconfig/network-scripts/"
  become: yes

- name: Restart NetworkManager for the new interface
  shell: systemctl restart NetworkManager
  become: yes

- name: Bring up the HostOnly interface
  shell: ifup ens33
  become: yes

- name: Run Elastic Setup
  command: bash /vagrant/scripts/setup-elastic.sh
  become: yes

- name: Install Operator
  command: bash /vagrant/scripts/install-operator.sh
  become: yes
